// vue-nuxt/basic/components/navbar.vue
<template>
  <div>
    <nav class="navbar">
      <NuxtLink to="/" class="links" exact-active-class="active">Home</NuxtLink>
      <NuxtLink to="/about" class="links" exact-active-class="active">About</NuxtLink>
      <NuxtLink to="/contact" class="links" exact-active-class="active">Contact</NuxtLink>
      <NuxtLink to="/posts" class="links" exact-active-class="active">Posts</NuxtLink>
      <NuxtLink to="/admin/posts" class="links" exact-active-class="active">Admin</NuxtLink>
    </nav>
  </div>
</template>

// react/router/src/components/navbar.jsx
import { NavLink } from "react-router-dom"

export default function navbar() {
  return (
    <>
      <nav className="navbar">
        <NavLink to="/" className="links" >Home</NavLink>
        <NavLink to="/about" className="links">About</NavLink>
        <NavLink to="/contact" className="links">Contact</NavLink>
        <NavLink to="/admin" className="links">Admin</NavLink>
      </nav>
    </>
  )
}
