// react/react-blog/src/views/client/user-posts.js
import React from 'react'
import { useState, useEffect } from 'react'
import { useParams } from 'react-router-dom'
import axios from 'axios'

export default function UserPosts() {
  const [data, setData] = useState([])
  const {id} = useParams()
 
  useEffect(() => {
    axios.get(`http://localhost:3000/api/client/${id}/posts`)
      .then((res) => setData(res.data))
      .catch((err) => console.log(err))
  }, [id])
  console.log(data)
  return (
    <>
      <h1>{id} Posts</h1>
      <div className='container'>
        <div className='row'>
          {data.map(item =>
            <div className='col-sm-6' key={item._id}>
              <div className='card'>
                <div className='card-body'>
                  <h2>{item.title}</h2>
                  <p>Date: {item.createdAt}</p>
                  <span>{String(item.body).substring(0,100)}</span>
                <div>
                <a href={`${item._id}`}>Read more...</a>
                </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  )
}

// nodejs/i18/src/views/client/user-posts.vue
<template>
  <div class="container">
    <h2>{{ owner }} Posts</h2>
    <a href="#" @click="getBack()">Return</a>
    <div class="row">
    <template v-for="item in posts" :key="item._id">
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <img :src="`/uploads/${item.imageName}`" alt="">
              <h5 class="card-title">{{ item.title }}</h5>
              <p class="card-subtitle mb-2 text-muted">
                {{ new Date(item.created_at).toLocaleDateString() }}
                <strong>{{ item.owner }}</strong>
              </p>
              <p class="card-text">{{ String(item.body).substring(0, 200) }}</p>
              <a :href="`/${item.owner}/post/${item._id}`" class="card-link">Read more...</a>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script>
import axios from "axios";

export default {
  data() {
    return {
      posts: {},
      owner: ''
    }
  },
  mounted() {
    this.getPosts()
  },
  methods: {
    async getPosts() {
      await axios.get(`/api/client/${this.$route.params.user}/posts`).then(res => {
        if (res.status == 200) {
          this.posts = res.data.posts
          this.owner = res.data.posts[0].owner
        }
      })
    },
    getBack(){
      window.history.back()
    }
  }
}

</script>
