// react-next/src/app/admin/users/[id]/page.jsx
import React from 'react'
import { getUsers } from '../page' //this com from page-cache

export default async function Details({params}) {
  const users = await getUsers()
  const user = users.filter(item => item.id == params.id)[0]
  return (
    <>
      <h1>User Details</h1>
      <ul>
        <li>{user.id}</li>
        <li>{user.name}</li>
        <li>{user.username}</li>
        <li>{user.email}</li>
      </ul>
    </>
  )
}

// vue-nuxt/pages/admin/users/[id].vue
<script setup>
  definePageMeta({
    layout:'admin-layout'
  })

  const { params } = useRoute()
  const { data } = await useFetch('https://jsonplaceholder.typicode.com/users/' + params.id)

</script>

<template>
  <div>
    <h1>User Details</h1>
    <ul>
      <li>
        <span>{{ data.id }}</span>
        <span>{{ data.name }}</span>
        <span>{{ data.email }}</span>
      </li>
      <button><NuxtLink to="/admin/users/">Back</NuxtLink></button>
    </ul>
  </div>
</template>
