// react/react-blog/src/views/client/index.js
import React from 'react'
import { useState, useEffect } from 'react'
import axios from 'axios'

export default function Index() {
  const [data, setData] = useState([])

  useEffect(() => {
    axios.get('http://localhost:3000/api/client/')
      .then((res) => setData(res.data))
      .catch((err) => console.log(err))
  }, [])
  console.log(data)
  return (
    <>
      <h1>Home</h1>
      <div className='container'>
        <div className='row'>
          {data.map(item =>
            <div className='col-sm-6' key={item._id}>
              <div className='card'>
                <div className='card-body'>
                  <h2>{item.title}</h2>
                  <p>{item.createdAt} <a href={`/${item.owner}/posts`}>{item.owner}</a></p>
                  <span>{String(item.body).substring(0,100)}</span>
                <div>
                  <a href={`${item.owner}/${item._id}`}>Read more...</a>
                </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </>
  )
}

// vue3/blog/src/views/client/index.vue
<template>
  <div class="container">
    <h2>All Posts</h2>
    <div class="row">
    <template v-for="item in posts" :key="item._id">
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <img :src="`/uploads/${item.image}`" alt="">
              <h5 class="card-title">{{ item.title }}</h5>
              <p class="card-subtitle mb-2 text-muted">
                {{ new Date(item.created_at).toLocaleDateString() }}
                <a :href="`/${item.owner}/posts`">{{ item.owner }}</a>
              </p>
              <p class="card-text">{{ String(item.body).substring(0, 200) }}</p>
              <a :href="`${item.owner}/post/${item._id}`" class="card-link">Read more...</a>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script>
import axios from "axios";

export default {
  data() {
    return {
      posts: {}
    }
  },
  mounted() {
    this.getPosts()
  },
  methods: {
    async getPosts() {
      await axios.get('/api/client').then(res => {
        if (res.status == 200) {
          this.posts = res.data.posts
        }
      })
    }
  }
}

</script>
