// nodejs/i18/src/views/auth/register.vue
<template>
  <div class="container border rounded p-5">
    <h3 style="margin-bottom: 30px;">Register</h3>
    <div class="mb-3 row">
      <label for="name" class="form-label">Name</label>
      <div>
        <input type="name" v-model="user.name" class="form-control" id="name">
        <div v-if="error.name" class="text text-danger mt-2">{{ error.name.message }}</div>
      </div>
    </div>
    <div class="mb-3 row">
      <label for="email" class="form-label">Email</label>
      <div>
        <input type="email" v-model="user.email" class="form-control" id="email">
        <div v-if="error.email" class="text text-danger mt-2">{{ error.email.message }}</div>
        <div v-if="emailDup" class="text text-danger mt-2">{{ emailDup }}</div>
      </div>
    </div>
    <div class="mb-3 row">
      <label for="inputPassword" class="form-label">Password</label>
      <div>
        <input type="password" v-model="user.password" class="form-control" id="inputPassword">
        <div v-if="error.password" class="text text-danger mt-2">{{ error.password.message }}</div>
      </div>
    </div>
    <div class="mb-3 row">
      <label for="confirm_password" class="form-label">Confirm Password</label>
      <div>
        <input type="password" v-model="user.passwordConfirm" class="form-control" id="confirm_password">
        <div v-if="passwordMatch" class="text text-danger mt-2">{{ passwordMatch }}</div>
      </div>
    </div>
    <div class="d-grid">
      <button class="btn btn-dark btn-lg" @click="registerUser()">Register</button>
    </div>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  data() {
    return {
      user: {
        name: '',
        email: '',
        password: '',
        passwordConfirm: ''
      },
      error: {},
      emailDup: '',
      passwordMatch: ''
    }
  },
  methods: {
    async registerUser() {
      this.emailDup = ''
      this.error = ''
      this.passwordMatch = ''
      if(this.user.password !== this.user.passwordConfirm){
        this.passwordMatch = 'Password not match!'
        return false
      }
      await axios.post('/api/register', { user: this.user }).then(res => {
        if (res.status == 201) {
          this.emailDup = res.data
          return false
        }
        if (res.data.errors == undefined) {
          this.$router.push('/login')
        } else {
          this.error = res.data.errors
        }
      })
    }
  },
}
</script>

// react/react-blog/src/views/auth/register.js
import React from 'react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import axios from 'axios'

export default function Register() {
  const [data, setData] = useState({
    username: '',
    email: '',
    password: '',
    confirmPassword: ''
  })
  const [error, setError] = useState({
    username: '',
    email: '',
    password: '',
    confirmPassword: '',
    duplicate:''
  })

  let navigate = useNavigate()

  const handelInputs = (e) => {
    setData(values => ({ ...values, [e.target.name]: e.target.value }))
  }
  const createUser = (e) => {
    e.preventDefault()
    if (data.password === data.confirmPassword) {
      axios.post('http://localhost:3000/api/auth/register', data)
      .then((res) => {
          if (res.data.errors) {
            setError(res.data.errors)
            return false
          } else if(res.status === 201){
            setError({duplicate:res.data})
            return false
          } else {
            setError({})
            setTimeout(() => {
              navigate('/user/posts')
            }, 1000)
          }
        })
        .catch((err) => console.log(err))
    } else {
      setError({ confirmPassword: 'Password not match!' })
    }
  }
  return (
    <>
      <h3 style={{ marginBottom: "30px" }}>Register</h3>
      <div className="container border rounded p-5">
        <div className="mb-3 row">
          <label htmlFor="name" className="form-label">Name</label>
          <div>
            <input type="name" onChange={handelInputs} name="username" className="form-control" id="username" />
            {error.username ? <div className="text text-danger mt-2">{error.username.message}</div> : ''}
          </div>
        </div>
        <div className="mb-3 row">
          <label htmlFor="email" className="form-label">Email</label>
          <div>
            <input type="email" onChange={handelInputs} name="email" className="form-control" id="email" />
            {error.email ? <div className="text text-danger mt-2">{error.email.message}</div> : ''}
            {error.duplicate ? <div className="text text-danger mt-2">{error.duplicate}</div> : ''}
          </div>
        </div>
        <div className="mb-3 row">
          <label htmlFor="inputPassword" className="form-label">Password</label>
          <div>
            <input type="password" onChange={handelInputs} name="password" className="form-control" id="inputPassword" />
            {error.password ? <div className="text text-danger mt-2">{error.password.message}</div> : ''}
          </div>
        </div>
        <div className="mb-3 row">
          <label htmlFor="confirm_password" className="form-label">Confirm Password</label>
          <div>
            <input type="password" onChange={handelInputs} name="confirmPassword" className="form-control" id="confirm_password" />
            {error.confirmPassword ? <div className="text text-danger mt-2">{error.confirmPassword}</div> : ''}
          </div>
        </div>
        <div className="d-grid">
          <button className="btn btn-dark btn-lg" onClick={createUser}>Register</button>
        </div>
      </div >
    </>
  )
}
