// react/basic/src/components/Navbar.js
import React from 'react'
import { NavLink } from 'react-router-dom'

export default function Navbar() {
  return (
    <div className='navbar'>
      <NavLink to="/" className="links" >Home</NavLink>
      <NavLink to="/props" className="links" >Props</NavLink>
      <NavLink to="/list" className="links" >List</NavLink>
      <NavLink to="/admin" className="links" >Admin</NavLink>
    </div>
  )
}

// vue3/2-router/router/src/components/navbar.vue
<script setup>
  import { RouterLink } from 'vue-router';
</script>

<template>
  <div>
    <nav class="navbar">
      <RouterLink to="/" class="links" exact-active-class="active">Home</RouterLink>
      <RouterLink to="/admin" class="links" exact-active-class="active">Admin</RouterLink>
    </nav>
  </div>
</template>
