// nodejs/i18/src/views/admin/create.vue
<template>
  <div>
    <div class="container">
      <h1>Create New Post</h1>
      <h3 class="text text-success text-center">{{ message }}</h3>
      <form @submit.prevent id="form" class="border rounded p-4">
        <div class="mb-3 row">
          <label for="title">Title</label>
          <div>
            <input type="text" class="form-control" v-model="post.title">
            <div class="text text-danger mt-2" v-if="error.title">{{ error.title }}</div>
          </div>
          <label for="body">Body</label>
          <div>
            <textarea class="form-control" rows="10" v-model="post.body" id="body"></textarea>
            <div class="text text-danger mt-2" v-if="error.body">{{ error.body }}</div>
          </div>
          <label for="title">Image</label>
          <div>
            <input type="file" ref="file"  @change="selectImage($event)" accept="image/*">
            <div class="text text-danger mt-2" v-if="error.file">{{ error.file }}</div>
          </div>
          <div class="d-grid mt-3">
            <button class="btn btn-dark" @click="createPost()">Create</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  
</template>
<script>
import axios from 'axios'
export default {
  name: 'Index',
  data() {
    return {
      post: {
        title: '',
        body: '',
      },
      data: '',
      message: '',
      error: {}
    }
  },
  methods: {
    selectImage(event){
      this.data = new FormData()
      this.data.append('file', event.target.files[0])
      this.data.append('post', JSON.stringify(this.post))
    },
    async createPost() {
    if(this.post.title == ''){
      this.error = {title: 'Title cant bu null!'}
    } else if(this.post.body == ''){
      this.error = {body: 'Body cant be null!'}
    } else if(this.post.imageName == ''){
      this.error = {file: 'No selected file!'}
    } else {
        await axios.post('/api/admin/create', this.data).then(res => {
          if (res.status == 200) {
            this.message = res.data
          }
        })
      }
    }
  },
}
</script>
<style></style>

// react/react-blog/src/views/user/create.js
import React from 'react'
import { useState } from 'react'
import axios from 'axios'

export default function Create() {
  const [data, setData] = useState({
    title: '',
    body: ''
  })
  const [file, setFile] = useState()

  const handelInputs = (e) => {
    const val = e.target.value
    setData(values => ({...values, [e.target.name]: val}))
  }
  const selectImage = (e) => {
    setFile(e.target.files[0])
  }
  const createPost = (e) => {
    e.preventDefault()
    const frmData = new FormData()
    frmData.append('file', file)
    frmData.append('post', JSON.stringify(data))
    axios.post('http://localhost:3000/api/user/posts/create', frmData)
    .then((res) => {
      console.log(res.data)
    })
    .catch((err) => console.log(err))
  }
  return (
    <>
      <h1>Create New Products</h1>
      <div className='container'>
        <form onSubmit={createPost} id="form" className="border rounded p-4" encType="multipart/form-data">
          <div className="mb-3 row">
            <label htmlFor="title">Title</label>
            <div>
              <input type="text" className="form-control" name="title" onChange={handelInputs} />
              {/* <div className="text text-danger mt-2" v-if="error.title"></div> */}
            </div>
            <label htmlFor="body">Body</label>
            <div>
              <textarea className="form-control" rows="10" name="body" id="body" onChange={handelInputs}></textarea>
              {/* <div className="text text-danger mt-2" v-if="error.body"></div> */}
            </div>
            <label htmlFor="title">Image</label>
            <div>
              <input type="file" name="file" onChange={selectImage} accept="image/*" />
              <div className="text text-danger mt-2" v-if="error.file"></div>
            </div>
            <div className="d-grid mt-3">
              <button type='submit' className="btn btn-dark">Create New Post</button>
            </div>
          </div>
        </form>
      </div>
    </>
  )
}
