// react/0-router/src/views/Admin.js
import React from 'react'
import { Outlet, Link } from 'react-router-dom'

function Admin() {
  return (
    <div>
      <h1>Dashboard</h1>
      <nav className='navbar'>
        <Link to="admin" className='links'>Users</Link>
        <Link to="settings" className='links'>Settings</Link>
      </nav>
      <main className='router'>
        <Outlet />
      </main>
    </div>
  )
}

export default Admin

// vue3/2-vue-npm-version/router/basic/src/views/Admin.vue
<template>
  <div>
    <nav class="admin-nav">
       <router-link class="links" to="/admin">Users</router-link>
       <router-link class="links" to="/settings">Settings</router-link>
    </nav>
    <RouterView class="router"/>
  </div>
</template>

<script>
export default {
  name: "Account Page",
  data() {
    return {
      title: "Dashboard"
    }
  },
  methods: {
  }
};
</script>

<style scoped>
.admin-nav{
  margin: 50px 0;
}
  .links{
    margin: 0 15px;
    font-size: 18px;
  }
</style>
