// react/seo/src/views/home.jsx
import { Helmet } from "react-helmet"
export default function Home() {
  return (
    <>
    <Helmet>
      <title>Home</title>
      <meta name="description" content="Home content" />
      <meta name="keywords" content="react, meta tags, seo" />
      <meta name="author" content="Your Name" />
    </Helmet>
      <h1>Home</h1>
    </>
  )
}

// vue3/seo/src/views/client/home.vue
<template>
  <div>
    <h1>{{ title }}</h1>
    <h1 v-if="!$store.state.auth">Please login...</h1>
    <h1 v-else>Welcome {{ $store.state.auth }}</h1>
  </div>
</template>

<script>
import {useHead} from '@vueuse/head'
useHead({
  title:'Home',
  meta: [
    {
      name: 'description',  content:'Meta Home Page'
    }
  ]
})
export default {
  name:'Home',
  data () {
    return {
      title:'Home'
    }
  }
};
</script>
