// auth/by-email/src/components/Navbar.vue
<template>
  <div>
    <nav>
      <router-link to="/" class="links">Home</router-link>
      <router-link to="/login" class="links">Login</router-link>
      <router-link to="/register" class="links">Register</router-link>
      <router-link to="" class="links" @click="logout()">Logout</router-link>
    </nav>
  </div>
</template>

<script>
 export default {
  name:'Navbar',
  data () {
    return {

    }
  },
  methods: {
    logout(){
      localStorage.removeItem('token')
      this.$router.push('/login')
    }
  },
 }
</script>
<style scoped>
  nav{
    display: flex;
  }
  .links{
    margin: 10px;
  }
  .links{
    text-decoration: none;
  }
  .active{
    color: green;
  }
</style>

// react/react-state/localstorage/src/components/navbar.jsx
import { NavLink, useNavigate } from "react-router-dom"

export default function Navbar() {
  const navigate = useNavigate()

  const deleteLoggedUser = () => {
    localStorage.removeItem("loggedUser");
    navigate('/login')
  }
  return (
    <>
      <nav className="navbar">
        <div>
          <NavLink to="/" className="links">Home</NavLink>
          <NavLink to="/admin" className="links">Admin</NavLink>
        </div>
        <div>
          <NavLink to="/login" className="links">Login</NavLink>
          <button className="logout" onClick={deleteLoggedUser}>Logout</button>
        </div>
      </nav>
    </>
  )
}
