// vue-nuxt/basic/components/navbar.vue
<template>
  <div>
    <nav class="navbar">
      <NuxtLink to="/" class="links" exact-active-class="active">Home</NuxtLink>
      <NuxtLink to="/about" class="links" exact-active-class="active">About</NuxtLink>
      <NuxtLink to="/contact" class="links" exact-active-class="active">Contact</NuxtLink>
      <NuxtLink to="/posts" class="links" exact-active-class="active">Posts</NuxtLink>
      <NuxtLink to="/admin/posts" class="links" exact-active-class="active">Admin</NuxtLink>
    </nav>
  </div>
</template>

// react-next/crud-mongodb/app/components/navbar/page.jsx
"use client";
import React from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";

export default function Navbar() {
  const router = usePathname()
  return (
    <>
      <nav className="navbar">
        <Link href="/" className={router === '/' ? "active" : "links"} >Home</Link>
        <Link href="/about" className={router === '/about' ? "active" : "links"} >About</Link>
        <Link href="/contact" className={router === '/contact' ? "active" : "links"} >Contact</Link>
        <Link href="/admin/users" className={router === '/admin/users' ? "active" : "links"} >Users</Link>
        <Link href="/admin/adduser" className={router === '/admin/adduser' ? "active" : "links"} >Add User</Link>
      </nav>
    </>
  );
}
