// react/router/layouts/src/views/admin/details.jsx
import { useParams, useNavigate } from "react-router-dom"
import { Helmet } from "react-helmet"

export default function Details() {
  const navigate = useNavigate()

  const {id} = useParams()
  return (
    <>
    <Helmet>
      <title>User Details</title>
      <meta name="description" content="User Details content" />
      <meta name="keywords" content="react, meta tags, seo" />
      <meta name="author" content="Your Name" />
    </Helmet>
      <h2>User Details</h2>
      <h1>{id}</h1>
      <button onClick={() => navigate('/admin')}>Back</button>
    </>
  )
}

// vue3/seo/src/views/admin/details.vue
<template>
  <div>
    <h1>{{ $route.params.id }}</h1>
    <button @click="$router.push('/admin/posts')">Back</button>
  </div>
</template>
<script>
import {useHead} from '@vueuse/head'
useHead({
  title:'Details',
  meta: [
    {
      name: 'description',  content:'Meta Details Page'
    }
  ]
})
export default {
  name: 'Details',
  data() {
    return {
    }
  },
 
  //local route guard
  // beforeRouteEnter(to, from, next) {
  //   alert('You have no permission for this page')
  //   if (to.name == '/') {
  //     next()
  //   }
  // }
}
</script>
