// react/react-blog/src/views/user/edit.js
import React from 'react'
import { useState, useEffect } from 'react'
import { useParams } from 'react-router-dom'
import axios from 'axios'

export default function Edit() {
  const {id} = useParams()
  const [data, setData] = useState({
    title: '',
    body: '',
    _id: id
  })
  const [file, setFile] = useState()

  useEffect(() => {
    axios.get(`http://localhost:3000/api/user/posts/post/${id}`)
      .then((res) => setData(res.data))
      .catch((err) => console.log(err))
  }, [id])

  const handelInputs = (e) => {
    const val = e.target.value
    setData(values => ({...values, [e.target.name]: val}))
  }
  const selectImage = (e) => {
    setFile(e.target.files[0])
  }
  const updatePost = (e) => {
    e.preventDefault()
    const frmData = new FormData()
    frmData.append('file', file)
    frmData.append('post', JSON.stringify(data))
    axios.post('http://localhost:3000/api/user/posts/update', frmData)
    .then((res) => {
      console.log(res.data)
    })
    .catch((err) => console.log(err))
  }
  return (
    <>
      <h1>Edit</h1>
      <div className='container'>
        <form onSubmit={updatePost} id="form" className="border rounded p-4" encType="multipart/form-data">
          <div className="mb-3 row">
            <label htmlFor="title">Title</label>
            <div>
              <input type="text" className="form-control" name="title" value={data.title} onChange={handelInputs} />
              {/* <div className="text text-danger mt-2" v-if="error.title"></div> */}
            </div>
            <label htmlFor="body">Body</label>
            <div>
              <textarea className="form-control" rows="10" name="body" id="body" value={data.body} onChange={handelInputs}></textarea>
              {/* <div className="text text-danger mt-2" v-if="error.body"></div> */}
            </div>
            <label htmlFor="title">Image</label>
            <img className='updateImage' src={`/uploads/${data.imageName}`}  alt="no image"/>
            <div>
              <input type="file" name="file" onChange={selectImage} accept="image/*" />
              <div className="text text-danger mt-2" v-if="error.file"></div>
            </div>
            <div className="d-grid mt-3">
              <button type='submit' className="btn btn-dark">Update Post</button>
            </div>
          </div>
        </form>
      </div>
    </>
  )
}

// nodejs/i18/src/views/admin/edit.vue
<template>
  <div>
    <div class="container">
      <h1>Create New Post</h1>
      <button class="btn btn-secondary" @click="getBack()">Return</button>
      <h3 class="text text-success text-center">{{ message }}</h3>
      <form @submit.prevent id="form" class="border rounded p-4">
        <div class="mb-3 row">
          <label for="title">Title</label>
          <div>
            <input type="text" class="form-control" v-model="post.title">
            <div class="text text-danger mt-2" v-if="error.title">{{ error.title }}</div>
          </div>
          <label for="body">Body</label>
          <div>
            <textarea class="form-control" rows="10" v-model="post.body" id="body"></textarea>
            <div class="text text-danger mt-2" v-if="error.body">{{ error.body }}</div>
          </div>
          <label for="title">Image</label>
          <img :src="`/uploads/${post.imageName}`" alt="" class="updateImage">
          <div class="mt-3">
            <input type="file" ref="file"  @change="selectImage($event)" accept="image/*">
            <div class="text text-danger mt-2" v-if="error.file">{{ error.file }}</div>
          </div>
          <div class="d-grid mt-3">
            <button class="btn btn-dark" @click="updatePost()">Update</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  
</template>
<script>
import axios from 'axios'
export default {
  name: 'Index',
  data() {
    return {
      post: {
        title: '',
        body: '',
        imageName: ''
      },
      data: '',
      message: '',
      error: {},
      file: null
    }
  },
  mounted(){
    this.getPost()
  },
  methods: {
    async getPost() {
      await axios.get(`/api/admin/post/${this.$route.params.id}`).then(res => {
        if (res.status == 200) {
          this.post = res.data.post
        }
      })
    },
    selectImage(event){
      this.file =  event.target.files[0]
    },
    async updatePost() {
      this.data = new FormData()
      if(this.file !== null){
        this.data = new FormData()
        this.post.imageName = `${this.$store.state.auth._id}.${this.file.name}`
        this.data.append('file', this.file)
      }
      this.data.append('post', JSON.stringify(this.post))
      if(this.post.title == ''){
        this.error = {title: 'Title cant bu null!'}
      } else if(this.post.body == ''){
        this.error = {body: 'Body cant be null!'}
      } else if(this.post.imageName == ''){
        this.error = {file: 'No selected file!'}
      } else {
        await axios.post('/api/admin/update', this.data).then(res => {
          if (res.status == 200) {
            this.error = {}
            this.message = res.data
            setTimeout(() => {
              this.$router.push('/admin/post/'+this.$route.params.id)
            }, 2000)
          }
        })
      }
    },
    getBack(){
      window.history.back()
    }
  }
}
</script>
<style></style>
