// react/router/src/components/navbar.jsx
import { NavLink } from "react-router-dom"

export default function navbar() {
  return (
    <>
      <nav className="navbar">
        <NavLink to="/" className="links" >Home</NavLink>
        <NavLink to="/about" className="links">About</NavLink>
        <NavLink to="/contact" className="links">Contact</NavLink>
        <NavLink to="/admin" className="links">Admin</NavLink>
      </nav>
    </>
  )
}

// vue3/nuxt/layouts/components/navbar.vue
<template>
  <div class="navbar">
    <RouterLink to="/" class="links" exact-active-class="active">Home</RouterLink>
    <RouterLink to="/about" class="links" exact-active-class="active">About</RouterLink>
    <RouterLink to="/admin" class="links" exact-active-class="active">Admin</RouterLink>
  </div>
</template>
