// vue3/option-api/router/child-router/src/views/admin/Profile.vue
<template>
  <div>
    <h2>User - {{ $route.params.id }}</h2>
    <br/>
    <input type="button" @click="goBack()" value="Go Back"/>
  </div>
</template>

<script>
export default {
  name:'Profile',
  data () {
    return {
      title:'Profile'
    }
  },
  methods:{
    goBack(){
      this.$router.back()
      // this.$router.push('/admin')
    }
  }
};
</script>

<style>
input{
  border: 1px solid #ddd;
  padding: 10px 40px;
  border-radius: 5px;
  cursor: pointer;
}
input:hover{
  transform: scale(1.1);
}
</style>

// react/http-request/src/views/Profile.js
import React from 'react'
import { useParams, useNavigate } from 'react-router-dom'

function Profile() {
  const params = useParams()
  const navigate = useNavigate()
  return (
    <div>
      <h1>Profile</h1>
      <br/>
      <h2>User {params.id}</h2>
      <br/>
      <input type='button' value="Go Back"  onClick={() => navigate(-1)} className='input-btn'/>
    </div>
  )
}

export default Profile
