// react/forms/src/views/Login.js
import React from 'react'
import { Form, redirect } from 'react-router-dom'

export const loginFunction = async({request}) => {
  console.log(request)
  const data = await request.formData()
  const postData = {
    name: data.get('name'),
    password: data.get('password')
  }
  console.log(postData)
  return redirect('/')
}

function Login() {
  return (
    <div>
      <h2>Login</h2>
      <div>
        <Form action='/login' method='POST' className='login-form'>
          <input type='text' name="name" placeholder='Name...'/>
          <input type='password' name="password" placeholder='Password...'/>
          <input type="submit" className="login-btn" value="Login"/>
        </Form>
      </div>
    </div>
  )
}


export default Login

// laravel/0-laravel-core/vue-nuxt-laravel/auth/client/pages/Login.vue
<template>
  <div>
    <h2>Login Page</h2>

    <form @submit.prevent="login()">
      <input type="text" ref = "email" placeholder="Email">
      <input type="text" ref = "password" placeholder="Password">
      <input type="submit" value="Login">
    </form>
  </div>
</template>
<script>
export default {
  auth:'guest',
  data () {
    return {
      
    }
  },
  mounted(){
    this.$axios.$get('/sanctum/csrf-cookie')
  },
  methods:{
    async login(){
      const loginUser= {
        email:this.$refs.email.value,
        password:this.$refs.password.value
      }
      try {
        await this.$auth.loginWith('laravelSanctum', {data:loginUser})
        this.$store.commit('setAuth', this.$auth.loggedIn)
        this.$router.push('/dashboard')
      } catch (error) {
        if (error.response.status === 401) {
          console.log('Invalid User');
        }
      }
    }
  }
}
</script>
